version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=${PYTHONPATH}
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true  # ファイル監視用（必要に応じて）